version: '3.8'
   
services:
  runbot:
    build: ./
    command: ./runbot
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./:/usr/bot
    environment:
      - TZ=EET
      - DEBIAN_FRONTEND=noninteractive 

  mongodb:
    restart: always
    image: mongo:focal
    env_file:
      - .env      
    ports:
        - 2121:27017
    environment:
      - TZ=EET
      - DEBIAN_FRONTEND=noninteractive 

