version: '3.3'
   
services:
  runbot:
    build: ./
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./:/usr/bot
    restart: always
    environment:
      - TZ=EET
      - DEBIAN_FRONTEND=noninteractive
    # entrypoint: /usr/bot/runbot

  mongodb:
    restart: always
    image: mongo:focal
    env_file:
      - .env      
    ports:
        - 2121:27017
    environment:
      - TZ=EET
      - DEBIAN_FRONTEND=noninteractive 

